README.md
Running `bundle update` would update all the gems in the application, better run just `bundle install` to install this particular gem.
I've also updated the version number, but I'd just leave it out entirely and use `gem 'counter_culture'` to install the latest version.
=> update readme about gem installation instructions

lib/counter_culture.rb, spec/counter_culture_spec.rb, spec/models/user.rb
If the counting table has a default_scope that contains a JOIN, counter_culture crashes with an error like this:
```
Ambiguous column name: id: SELECT  DISTINCT "users".* FROM "users" LEFT OUTER JOIN companies WHERE (id = 53)  ORDER BY "users"."id" ASC LIMIT 1
```
I added some tests and a fix. ;)
=> `Ambiguous column name id` fix

lib/counter_culture.rb
There is a weird behaviour of config `belongs_to_required_by_default` on Rails 5.0.0.rc2 when gem is not playing nice with the rails hooks.
Related rails/rails/issues/23589
=> Use `ActiveSupport.on_load` to hook into ActiveRecord

lib/counter_culture.rb, lib/counter_culture/reconciler.rb
Hi.
I'd like to use this gem in my padrino project. Padrino hasn't depend on activesupport now, so these components should be `require`d .
What do you think?
=> add required components of activesupport

lib/counter_culture/reconciler.rb
We had to update over 10 mil records.  Wrapping each batch in #counter_culture_fix_counts in a transaction reduces each update query time from about 8.0ms to 0.3ms.  In total, saved us waiting >24 hours for the update to complete.
before:
after:
=> wrap fix_counts in transactions

spec/counter_culture_spec.rb, spec/spec_helper.rb
Have started working on some changes to counter culture. It's frustrating to have a test run with such long pauses. I'm not 100% sure why such large numbers are needed, but I think the large numbers could only happen in CI where the long pause won't be noticed.
total test run before PR: ~ 30s
total test run after PR: ~ 5s
=> Reduce counts of batch-testing specs (except in CI)

lib/counter_culture/counter.rb, spec/counter_culture_spec.rb, spec/models/review.rb, spec/schema.rb
We should be able (like in Rails) touch custom columns when we specify column name instead true  for touch. 
counter_culture :product, touch: :rexiews_updated_at
=> support custom touch column

README.md
Hi! 
This PR is just updating the documentation with new hash syntax introduced by ruby 1.9. I'm using counter culture with this new syntax in my project and everything is working fine.
=> Use ruby >= 1.9 hash syntax

spec/spec_helper.rb
stops the local migrations from printing out
=> reduce noise in test runs when running locally

lib/counter_culture/counter.rb
When using counter_culture with a non-Rails project, the Rails version conditionals are failing (because `Rails` is not defined). This PR replaces those conditionals with checks for the ActiveRecord version.
I've successfully verified that this change allows it to work with a project that relies on ActiveRecord (but not Rails).
=> Fix version check (should check ActiveRecord instead of Rails)

lib/generators/counter_culture_generator.rb, lib/generators/templates/counter_culture_migration.rb.erb
In Rails > 5 need to insert rails version to migrations. 
This fix inserting this version only for Rails versions > 5
Caused by:
StandardError: Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:
class AddMessagesCountToConversationies < ActiveRecord::Migration[4.2]
=> [fix] generate migration template with version for rails >= 5

README.md, lib/counter_culture/extensions.rb, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb
As discussed in #210, I'm opening a PR to allow updating of timestamps for `counter_culture_fix_counts`. I appreciate your feedback.
=> Allow updating of timestamps when fixing counts

Gemfile, README.md, lib/counter_culture/extensions.rb, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb, spec/models/soft_delete_discard.rb, spec/models/soft_delete_paranoia.rb, spec/schema.rb
This adds support for properly counting things when using the [Discard](https://github.com/jhawthorn/discard) gem for soft deletes.
=> Support Discard for soft-deletes

CHANGELOG.md, README.md, lib/counter_culture/counter.rb, lib/counter_culture/extensions.rb, spec/counter_culture_spec.rb, spec/models/review.rb
This is an artifact of updates running after commit by default, which is
no longer the default, or in fact even tested. It causes to problems as
demonstrated by the new (formerly failing) test case.
This also deprecates execute_after_commit, as it is currently untested
and there is no real reason to use it anymore.
Fixes #221.
=> Don't wrap updates in counter_culture_active

lib/counter_culture/extensions.rb, spec/counter_culture_spec.rb
Hi,
this fixes bug when calling destroy on already discarded record (when using Discard for soft-deletes) - counts are currently updated twice (once when discard is called and once when destroy is called).
=> Don't update counts when hard-destroying discarded records

lib/counter_culture/extensions.rb, spec/counter_culture_spec.rb
Fixes #228 
With a new version of paranoia gem (>=2.3.0), I have the same issue with decrement counting of a model when I call the  `really_destroy!` method.
I have created the fix for this issue on this MR. 
Please review and merge it. 
Thank you!
=> Decrement counter when using paranoia really_destroy!

lib/counter_culture/extensions.rb
In our application `db:drop` was failing when the environment loaded a model that called `counter_culture`.  This was due to initializing a new instance which in turn hit the database.  See backtrace is at the bottom of this post.
The change in this PR accomplishes the same check without needing to initialize a brand new object which fixes our issue.  The issue in our app is pretty obscure and it would take me awhile to create a minimal reproducible test case.  However I believe this is a positive change in general since it decouples the `counter_culture` method from the model initialization process.
```
ActiveRecord::NoDatabaseError: FATAL:  database "test" does not exist
ruby/2.4.0/gems/activerecord-5.1.6.1/lib/active_record/connection_adapters/postgresql_adapter.rb:701:in `rescue in …
```
=> Replace initializing instance with checking instance_methods

README.md, lib/counter_culture/extensions.rb, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb
to make it possible to limit the number of records which get updated.
For instance, we have quite a big number of records and running periodically on all records might not work so it would make sense to run periodically only on a subset of the records and schedule it to different times.
Does this make sense?
=> Implement where option to Reconcile

lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb
Hey @magnusvk,
in commit https://github.com/magnusvk/counter_culture/commit/5a74d3c611c9057058429aafe3cf88a68d48e112 unfortunately the logging of the reconciler got broken. The ``<<`` operation was used for a reason to not produce a new line after each batch gets processed, maybe this was not clear in my code 😢 
Currently this is was the reconciler logs in verbose mode:
```
I, [2019-04-16T10:20:24.578702 #33762]  INFO -- : Performing reconciling of SimpleDependent#simple_main.
I, [2019-04-16T10:20:24.646091 #33762]  INFO -- : .
I, [2019-04-16T10:20:24.646271 #33762]  INFO -- : 
I, [2019-04-16T10:20:24.646607 #33762]  INFO -- : Finished reconciling of SimpleDependent#simple_main.
```
See the additional empty lines as well as it prints the `.` after processing a batch on a new line. As it …
=> Do no print a newline after processing each batch in Reconciler

lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb, spec/models/has_non_pk_id.rb, spec/models/user.rb, spec/schema.rb
Fixes #253
On PostgreSQL, if the table where the counts are stored doesn't have a primary_key specified (in our case, because it's actually a view), reconciliation fails with an error:
```
PG::GroupingError:
ERROR:  column "foo.users_count" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: ...foo".id, COUNT("users".id)*1 AS count, "foo..
```
This is because, according to the [Postgres docs](https://www.postgresql.org/docs/current/static/sql-select.html#SQL-GROUPBY):
> When GROUP BY is present, or any aggregate functions are present, it is not valid for the SELECT list expressions to refer to ungrouped columns except within aggregate functions or when the ungrouped column is functionally dependent on the grouped columns, since there would otherwise be more than …
=> Use a MAX() aggregation when fetching current count during reconciliation

README.md
I'm using it but option name is invalid.
So I fixed option name of Usage of README.md.
=> Fix counter_culture option name of README.md

README.md, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb, spec/models/city.rb, spec/models/prefecture.rb, spec/schema.rb
Hello.
I extended column_names option whose hash key accepts scope names as symbol, inspired by #245.
When you apply counter to a model that has a complex condition, you can use this scope as column_names's condition instead of Arel or SQL-style condition.
=> Extend column_names option to accepting scope name as symbol hash key

README.md, lib/counter_culture/extensions.rb, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb
The options start and finish are especially useful if you want multiple workers dealing with the same processing queue. You can make worker 1 handle all the records between id 1 and 9999 and worker 2 handle from 10000 and beyond by setting the `:start` and `:finish` option on each worker.
Description is taken from [find_in_batches docs in rails](https://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_in_batches)
```ruby
Product.counter_culture_fix_counts start: 10_000
Product.counter_culture_fix_counts finish: 10_000
Product.counter_culture_fix_counts start: 1000, finish: 2000
Product.counter_culture_fix_counts start: 2001, finish: 3000
```
Another use case of these options is to be able to restart the workers from specific id in case of failure in order to not revisit …
=> Add support for limits in batch processing

lib/counter_culture/reconciler.rb
After merging https://github.com/magnusvk/counter_culture/pull/282 I think these two variables are no longer used 🧹
=> Remove unused variables

CHANGELOG.md, counter_culture.gemspec, lib/counter_culture/version.rb, lib/generators/counter_culture_generator.rb
To include the Rails version not just for Rails 5.x but also future
versions.
=> Fix Rails version check in migration generator (Fixes #280)

lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb
Following up https://github.com/magnusvk/counter_culture/pull/279, when running multiple workers printing the batch index is useful information for not reprocessing same records, thanks to `start` and `finish` on `Model#counter_culture_fix_counts` we could restart from any point. In the following scenario, we know that we could restart the job from the last index processed by batch # 1
```
I, [2020-07-28T15:14:47.190722 #11698]  INFO -- : Performing reconciling of SimpleDependent#simple_main.
I, [2020-07-28T15:14:47.191807 #11698]  INFO -- : Processing batch #1.
I, [2020-07-28T15:14:47.191887 #11698]  INFO -- : Finshed batch #1.
I, [2020-07-28T15:14:47.192416 #11698]  INFO -- : Processing batch #2.
I, [2020-07-28T15:14:47.192416 #11698]  ERROR.....
```
=> Print batch index logs

lib/counter_culture/counter.rb, spec/models/review.rb, spec/schema.rb
I ran into the same problem as described in https://github.com/magnusvk/counter_culture/issues/278. First I've added a read only attribute to replicate the error in the test suite and then I changed the way the attributes are restored in the `previous_model` method. 
This way, it skips the overwritten setters which I think also makes sense to do since it's really the dirty changes as they will be persisted to the database. Aasm is also overwriting the setter and read only attributes are basically doing the same thing. I can't come up with a use case where this will not work but it's definitely good to think this trough. 
Closes https://github.com/magnusvk/counter_culture/issues/278
=> Add read only attribute to test model

lib/counter_culture/reconciler.rb
Thanks for creating this gem! It's super useful!
------------
On ruby 2.7.0, using the last argument as keyword parameters is deprecated (see [announcement](https://github.com/ruby/ruby/blob/4643bf5d55af6f79266dd67b69bb6eb4ff82029a/doc/NEWS-2.7.0#the-spec-of-keyword-arguments-is-changed-towards-30-)).
This PR fixes the following deprecation warning for ruby 2.7.1 on `lib/counter_culture/reconciler.rb:112`
```
counter_culture-2.6.0/lib/counter_culture/reconciler.rb:112: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
```
=> fixes last argument as keyword parameters deprecation warning

counter_culture.gemspec
This reduces unnecessary redirection from http://... to https://... when someone visits this gem's homepage via https://rubygems.org/gems/counter_culture or some tools or APIs that use the gem's metadata.
=> GitHub is HTTPS by default

counter_culture.gemspec, lib/counter_culture.rb, lib/counter_culture/extensions.rb
`execute_after_commit` option has been removed in v2.0.0.
=> Remove dependency to after_commit_action gem

README.md, lib/counter_culture/extensions.rb, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb
Add the support for the `column_name` option for `Model.counter_culture_fix_counts` to fix counts on the specific column. This allows us to skip the columns that have already been processed. This can be useful after running big DB changes that affect only one counter cache column.
=> Add a column_name option for fixing counts 

.travis.yml
Hi @magnusvk,
So the issue is because you customize the `install` phase in `.travis.yml` by explicitly updating dependencies (see [these lines](https://github.com/magnusvk/counter_culture/blob/3add9dfc6371c7610608b39b45788eaf51df118e/.travis.yml#L33-L36)), which makes them installed to a different directory `~/.rvm/gems` other than the default directory `vendor/bundle`. You may see [this](https://docs.travis-ci.com/user/caching/#caching-and-overriding-install-step) for reference. 
So now I've changed `cache` to point to the directory where gems are installed, and seems working. I restarted some jobs and I see that dependencies are being used from the cache. Thanks.
=> Cache bundler dependencies

README.md, lib/counter_culture/extensions.rb, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb, spec/models/city.rb, spec/schema.rb
* Returning a direct hash with a scope triggers loading of the schema cache in ActiveRecord, which can be undesirable
when your app is being booted. Using a Proc instead defers hitting this scope until it is actually called.
Fixes https://github.com/magnusvk/counter_culture/issues/298
It is discouraged to hit your database while code is being loaded during the boot process, this can affect such tasks as `db:create`, or building a Docker image that doesn't have access to a database. We can just use a Proc so the scope isn't called until it's actually needed.
=> Allows providing a Proc to column_names.

CHANGELOG.md, README.md, lib/counter_culture/extensions.rb, lib/counter_culture/reconciler.rb, lib/counter_culture/version.rb, spec/counter_culture_spec.rb
Provides the option of specifying the `polymorphic_classes` when calling `counter_culture_fix_counts`
I discovered that the `DISTINCT` query used in polymorphic relationships could be very expensive on large tables. The screenshot below shows that the majority of time spent in order creation on our marketplace platform is from this query.
The result of the query is the name of the classes to be updated. It's common in our use cases, [here at Patch](https://www.patch.io/), that we know the associated model or models that need to be updated. Therefore, providing this option will eliminate the potentially expensive query. All existing behavior is preserved.
This change is live in production on our fork of the repo. I used [db-query-matchers](https://github.com/civiccc/db-query-matchers) to …
=> Allow specifying the polymorphic_classes when calling counter_culture_fix_counts

lib/counter_culture/counter.rb, spec/counter_culture_spec.rb, spec/models/group.rb, spec/models/group_item.rb, spec/models/sub_group.rb, spec/schema.rb
This fixes an issue that happens when you have an array of relations, such as `[:sub_group, :group]` and their id keys are different. For example, one id key is `id` and another one is `uuid` or `uid` or anything else.
Before this fix, the method would `try` to access the last relation id using a previous relation key.
=> Fix primary key name for enumerable relations

lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb
Hi all 👋 
I believe I've come across a bug. This PR should fix it.
When using the `column_name` option on `counter_culture_fix_counts`, I wasn't seeing any changes to my column when the column name was dynamic (configured using the `column_names` option in my model).
On closer inspection, the problem only seemed to occur when I used a symbol to define the column name in the `column_names` hash. When I used a string, it worked as expected.  (Examples in the README use symbols).
I've patched this by simply ensuring that the column_name comparison in `Reconciler` is comparing String to String.
``` ruby
require "bundler/inline"
gemfile do
source "https://rubygems.org"
gem "activerecord", require: "active_record"
gem "sqlite3"
gem "counter_culture"
end …
```
=> Fix bug on counter_culture_fix_counts when column_name is a symbol

lib/counter_culture/extensions.rb, spec/counter_culture_spec.rb
For example, there are these models.
```ruby
class Book < ApplicationRecord
has_many :reviews
end
class Review < ApplicationRecord
belongs_to :book
counter_culture :book
end
```
I called review.destory method twice. I expected this decrements counter -1. But, this decrements counter -2 acutually.
I fixed it.
```ruby
book = Book.create
review = Review.create(book: book)
book.reload
expect(book.reviews_count).to eq 1
review.destroy
book.reload
expect(book.reviews_count).to eq 0
review.destroy
book.reload
expect(book.reviews_count).to eq 0 # actually, -1 
```
=> Fix issue that decrement counter cache is called multiple times

lib/counter_culture/extensions.rb, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb
The documentation states
> You can specify a scope instead of a where condition string for `column_names`. We recommend
providing a Proc that returns a hash instead of directly providing a hash: If you were to directly
provide a scope this would load your schema cache on startup which will break things like
`rake db:migrate`.
This doesn't work tho as the proc is immediately `call`-ed in the `counter_culture` method to check it's return value. To fix this I've moved the ArgumentError from the setup side to the runtime side.
=> Fix passing a proc to `column_names`

.circleci/config.yml
I'm not sure if Ruby 3.2 will work with Rails 6.0 or 6.1. One or both of those may need to be excluded.
=> Adds Ruby 3.2 to the CI matrix

lib/counter_culture/counter.rb, spec/counter_culture_spec.rb, spec/models/poly_employee.rb, spec/models/poly_image.rb, spec/models/poly_product.rb, spec/schema.rb
Allow reading the `primary_key` option on polymorphic associations when it's present instead of returning the association's `primary_key`.
Basically the issue is that I have an association defined such as:
```
belongs_to :target, polymorphic: true, foreign_key: :target_uid, primary_key: :uid
has_many :something_plurals, 
as: :target,
class_name: 'SomeClass',
inverse_of: :target,
foreign_key: :target_uid,
primary_key: :uid
```
and yet `counter_culture` gem was trying to hit `Target#id` because `uid` is not the primary column of the table for now.
So my fix is to bypass the reflection on primary key if it's explicitly part of the polymorphic definition.
=> Handle reading primary key option from polymorphic association

README.md, lib/counter_culture/extensions.rb, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb
Hello. We are using column_names method for recalculating total counters. And found a problem with the large SQL scope for update:
```ruby
class Attendance < ApplicationRecord
...
counter_culture :event,
column_name: :missing_attendees_count,
column_names: -> { {Attendance.can_not_participate => :missing_attendees_count} }
```
```ruby
ids_for_update = {id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}
Attendance.counter_culture_fix_counts(where: { Event.table_name => ids_for_update })
```
The current logic builds an SQL query like this:
```sql
SELECT "events".id, "events".id,
COUNT("attendances".id)*1 AS count,
MAX("events".missing_attendees_count) AS missing_attendees_count
FROM "events"
LEFT JOIN "attendances" AS attendances ON "events".id = attendances.event_id AND attendances.id IN (
/*<<LARGE …
```
=> Add options as an argument for column_names proc

spec/models/user.rb
Removed unnecessary conditional branching from user.rb.
Rails.version < "4.0.0" was dropped in https://github.com/magnusvk/counter_culture/pull/252
=> Remove condition when Rails.version < 4.0.0 in user.rb

lib/counter_culture/counter.rb, spec/counter_culture_spec.rb, spec/models/post.rb, spec/models/post_like.rb, spec/schema.rb
We recently encountered a bug that prevents object from being touched correctly. 
When counter_culture tries to find touch column, it uses counted model for `timestamp_attributes_for_update_in_model`. However, counted model might have no updated_at column, and we should check model with counters to find correct timestamp attributes.
This issue is illustrated in my first commit, and fixed in second commit.
=> Fix touching for counted models without updated_at

Appraisals, counter_culture.gemspec, gemfiles/rails_5.2.gemfile, gemfiles/rails_6.0.gemfile, gemfiles/rails_6.1.gemfile, gemfiles/rails_7.0.gemfile, gemfiles/rails_7.1.gemfile
It turns out Rails versions prior to 7.2 require a `sqlite3 ~> 1.4` and we need to lock that in our `Gemfile` for the tests to work.
=> Fix sqlite3 tests

README.md, lib/counter_culture.rb, lib/counter_culture/counter.rb, spec/counter_culture_spec.rb, spec/spec_helper.rb
Title says it all 😄 
This had been brewing in my mind for quite a while and I finally got to implement it. I wanted it to be completely opt-in and not affect the normal flow. Implementation is not ideal but I felt like I didn't have too many options based on the current level of coupling and abstractions. I think it's abstracted enough to make it easy to maintain and hard to break even in the current state. Am open for suggestions though!
**Fixes:**
https://github.com/magnusvk/counter_culture/issues/307
https://github.com/magnusvk/counter_culture/issues/354
<details><summary>Sums multiple counter updates for single column of a single target record</summary>
```sql
-- Before
UPDATE `authors` SET `authors`.`books_count` = COALESCE(`authors`.`books_count`, 0) + 1 WHERE `authors`.`id` = 1 …
```
=> Combine multiple updates into a single SQL per target row (N+1)

Appraisals, CHANGELOG.md, counter_culture.gemspec, gemfiles/rails_5.2.gemfile, gemfiles/rails_6.0.gemfile, gemfiles/rails_6.1.gemfile, gemfiles/rails_7.0.gemfile, gemfiles/rails_7.1.gemfile, gemfiles/rails_7.2.gemfile, lib/counter_culture/reconciler.rb, lib/counter_culture/with_connection.rb, lib/generators/counter_culture_generator.rb, spec/counter_culture_spec.rb, spec/models/review.rb, spec/models/user.rb, spec/schema.rb, spec/spec_helper.rb
Because it turns out that you can use ActiveRecord outside of Rails (today I learned!)
=> Use `ActiveRecord.version` instead of `Rails.version`

lib/counter_culture.rb, lib/counter_culture/configuration.rb, lib/counter_culture/counter.rb, lib/counter_culture/reconciler.rb, spec/counter_culture_spec.rb, spec/models/composite_group.rb, spec/models/composite_group_user.rb, spec/models/composite_user.rb, spec/schema.rb
Fixes #412 
This change allows `counter_culture` to be used for associations that make use of `primary_key/foreign_key` with array values.
I tested that this change doesn't affect backwards compatibility of existing functionality for older versions of activerecord, but the test setup is reliant on the format of composite primary keys supported in activerecord v7.2+.
Also this change is functional with and has tests for composite key functionality with:
- papertrail
- `aggregate_counter_updates`
- `counter_culture_fix_counts`
=> feat: allow composite primary keys for Rails v7.2+

lib/counter_culture/counter.rb, spec/counter_culture_spec.rb
Hi @magnusvk 
After the v3.10.0 of this change https://github.com/magnusvk/counter_culture/pull/407 we encountered the `FrozenError:
can't modify frozen attributes` error while the create/destroy. Because we have frozen associated object instance while counter_culture attempt update the attribute of instance.
This pull-request fix the issue and add test about it.
=> fix: FrozenError when associated instance is frozen

lib/counter_culture/counter.rb, spec/counter_culture_spec.rb, spec/models/product.rb
It turns out the old tests here weren't properly reloading and thus didn't catch this regression.
=> Fix regression for `foreign_key_values` by adding support for composite primary keys
