- counter_culture.gemspec
Repo moved from [bestvendor/counter_culture](https://github.com/bestvendor/counter_culture) to [magnusvk/counter_culture](https://github.com/magnusvk/counter_culture)
Update the `.gemspec` with the new homepage url
> Update homepage url

- README.md
- lib/counter_culture/counter.rb
- spec/counter_culture_spec.rb
- spec/models/conditional_dependent.rb
- spec/models/product.rb
- spec/models/review.rb
- spec/models/twitter_review.rb
If we have scenario like : 
`  counter_culture :image, column_name: :weight, delta_magnitude: Proc.new { daynamic value } `
then we can define delta_magnitude with a Proc or number, not just 1
> support delta_magnitude for dynamic update value

- Rakefile
- counter_culture.gemspec
Thanks for the gem, I'm using it in https://libraries.io 🍻
> Updated homepage link in gemspec

- lib/counter_culture/counter.rb
Make it optional in `counter_culture` whether the update should happen in or outside of the transaction. It should default to inside the transaction.
> Fixes: #120 | Move counter cache update back into transaction by default

- spec/counter_culture_spec.rb
- spec/models/person.rb
- spec/models/transaction.rb
- spec/schema.rb
So it was an error on our end. However if you want to keep the extra specs feel free!
> Create spec for issue#148

- spec/counter_culture_spec.rb
- spec/spec_helper.rb
Show all failures when running on CI test run
requires/includes #150
> Show all failure on ci test run

- lib/counter_culture/reconciler.rb
So that using this with PostgreSQL and schema namespaces will work
correctly.
> Correctly quote table names and use aliases consistently

- lib/counter_culture/extensions.rb
- lib/counter_culture/reconciler.rb
- spec/counter_culture_spec.rb
add batch_size to whitelisted options passed to Reconciler
> make use of batch_size parameter

- CHANGELOG.md
- README.md
- lib/counter_culture/counter.rb
- spec/counter_culture_spec.rb
See https://github.com/airblade/paper_trail/issues/1076
Fixes #216
> Use PaperTrail's new save_with_version when available

- lib/counter_culture/counter.rb
- spec/counter_culture_spec.rb
- spec/models/with_module/model1.rb
- spec/models/with_module/model2.rb
- spec/schema.rb
> Test that it works with a model that has a module

- .travis.yml
- CHANGELOG.md
- Gemfile
- spec/counter_culture_spec.rb
- test_rails_versions.sh
... and update to the latest Ruby patch versions in our test matrix.
> Drop support for unsupported Rails and Ruby versions

- README.md
- lib/counter_culture/extensions.rb
- lib/counter_culture/reconciler.rb
- spec/counter_culture_spec.rb
> Add verbose mode to Reconciler

- lib/counter_culture/counter.rb
... in case different models have different database connections.
> Use klass.connection instead to make sure we get the correct connection

- .travis.yml
- Appraisals
- gemfiles/rails_6.0.gemfile
- lib/counter_culture/counter.rb
- lib/counter_culture/reconciler.rb
> Fix and test Rails 6.0.0 release

- README.md
Thanks for creating this gem! It's super useful!
---
I ran into a problem referenced in https://github.com/magnusvk/counter_culture/issues/96, so I updated documentation.
Please take a look at it.
> Update document about Conditional counter cache

- README.md
- Add supported Ruby versions
- Enable syntax highlighting on Ruby code snippet
> Small improvements on README

- README.md
I was lucky to spot this in my specs. :sweat_smile:
> README: add note for start/finish options for counter_culture_fix_counts

- lib/counter_culture/reconciler.rb
- spec/counter_culture_spec.rb
- spec/models/comment.rb
- spec/schema.rb
This fixes https://github.com/magnusvk/counter_culture/issues/374
A screencast explaining it all if you want to watch it https://www.loom.com/share/feb8cb3597be4d6aa9e314ecd532210c
> Bugfix 374 - Correct polymorphic table name alias reference in join clauses

- lib/counter_culture/counter.rb
- spec/counter_culture_spec.rb
- spec/spec_helper.rb
Addresses https://github.com/magnusvk/counter_culture/issues/392#issue-2335855620
> Don't perform a query if the delta_magnitude is zero

- lib/counter_culture/counter.rb
- spec/counter_culture_spec.rb
- spec/models/article.rb
- spec/models/article_group.rb
- spec/schema.rb
- https://github.com/magnusvk/counter_culture/pull/344#issuecomment-1759167624
- https://github.com/magnusvk/counter_culture/pull/344#issuecomment-1841240129
Hi!
This PR will solve this problem.
My test code wasn't able to  completely reproduce the `mobility` behavior, but I think it covered test target.
- https://github.com/magnusvk/counter_culture/pull/344
Thank you for reading 😄
> skip not exists attribute in saved_changes

- lib/counter_culture/counter.rb
- spec/models/conversation.rb
fix for https://github.com/magnusvk/counter_culture/issues/408
> Fixed assign count to associated object when delegate
